### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by Jkgitau** [AstrobioMike/AstrobioMike.github.io#40] opened 2021-12-08 00:16 UTC
Thank you for the wonderful tutorials, you clearly leveling the steep learning curve in Bioinformatics. Any chance the content menu on the right of a page be set to auto hide to enhance readability. That will be great.

Thanks again

**Comment by AstrobioMike** [comment] 2021-12-11 07:08
Hi there, thanks for the kind words and suggestion :)

It should move to the top of the document automatically when the window size is small enough that it would overlap the text. I can confirm it behaves this way still on safari and chrome. 

Is that not working in your case? Or do you just not like it there at all? 

I haven't spent much time with html/css since initially building the site, and it took me an obscene amount of time to get the table of contents to work the way it does currently. So any layout changes like that would take quite a bit of time and effort from me  that I'm not sure I'll be able to dedicate to this unless there's an actual bug maybe. Sorry :/

**Comment by AstrobioMike** [comment] 2022-03-17 21:46
closing this for now, of course feel free to re-open if wanted :)

**Closed by AstrobioMike** 2022-03-17 21:46 UTC
Labels: problem
